"""add_action_mode_schema

Revision ID: 10cd786660ee
Revises: 98134cceb82f
Create Date: 2026-01-26 10:58:33.490907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10cd786660ee'
down_revision: Union[str, None] = '98134cceb82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('suggested_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gmail_label_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emailinsight.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailaction_email_id'), 'emailaction', ['email_id'], unique=False)
    op.create_index(op.f('ix_emailaction_id'), 'emailaction', ['id'], unique=False)
    op.create_index(op.f('ix_emailaction_user_id'), 'emailaction', ['user_id'], unique=False)
    op.add_column('user', sa.Column('action_mode', sqlmodel.sql.sqltypes.AutoString(), server_default='review_first', nullable=False))
    op.add_column('user', sa.Column('confidence_threshold', sa.Float(), server_default='0.85', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confidence_threshold')
    op.drop_column('user', 'action_mode')
    op.drop_index(op.f('ix_emailaction_user_id'), table_name='emailaction')
    op.drop_index(op.f('ix_emailaction_id'), table_name='emailaction')
    op.drop_index(op.f('ix_emailaction_email_id'), table_name='emailaction')
    op.drop_table('emailaction')
    # ### end Alembic commands ###
