"""add_onboarding_state

Revision ID: 174f9dd9f87f
Revises: d92f7fe374df
Create Date: 2026-01-26 13:17:46.268952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '174f9dd9f87f'
down_revision: Union[str, None] = 'd92f7fe374df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('selected_categories', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'selected_categories')
    # ### end Alembic commands ###
