"""add_gmail_integration

Revision ID: 1caba6c7af7b
Revises: 57ba65cc309d
Create Date: 2026-01-27 12:18:26.232648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1caba6c7af7b'
down_revision: Union[str, None] = '57ba65cc309d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gmail_scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gmail_scopes')
    # ### end Alembic commands ###
