"""Add auto_fetch_enabled to user

Revision ID: 2ecbe4090d10
Revises: 837a83b88eea
Create Date: 2026-02-23 21:16:08.304346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ecbe4090d10'
down_revision: Union[str, None] = '837a83b88eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auto_fetch_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auto_fetch_enabled')
    # ### end Alembic commands ###
