"""add_snoozed_email_table

Revision ID: 31abab51ef40
Revises: 560e8285590a
Create Date: 2026-02-12 22:46:10.476850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31abab51ef40'
down_revision: Union[str, None] = '560e8285590a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snoozedemail',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('snooze_until', sa.DateTime(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resurfaced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emailinsight.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snoozedemail_email_id'), 'snoozedemail', ['email_id'], unique=False)
    op.create_index(op.f('ix_snoozedemail_id'), 'snoozedemail', ['id'], unique=False)
    op.create_index(op.f('ix_snoozedemail_user_id'), 'snoozedemail', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snoozedemail_user_id'), table_name='snoozedemail')
    op.drop_index(op.f('ix_snoozedemail_id'), table_name='snoozedemail')
    op.drop_index(op.f('ix_snoozedemail_email_id'), table_name='snoozedemail')
    op.drop_table('snoozedemail')
    # ### end Alembic commands ###
