"""add_google_credentials

Revision ID: 544ccc4347e7
Revises: 1caba6c7af7b
Create Date: 2026-01-27 12:19:42.989874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '544ccc4347e7'
down_revision: Union[str, None] = '1caba6c7af7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_label',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gmail_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_label_gmail_id'), 'gmail_label', ['gmail_id'], unique=False)
    op.create_index(op.f('ix_gmail_label_id'), 'gmail_label', ['id'], unique=False)
    op.create_index(op.f('ix_gmail_label_user_id'), 'gmail_label', ['user_id'], unique=False)
    op.create_table('google_credential',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_credential_id'), 'google_credential', ['id'], unique=False)
    op.create_index(op.f('ix_google_credential_user_id'), 'google_credential', ['user_id'], unique=True)
    op.drop_column('user', 'gmail_scopes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gmail_scopes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_google_credential_user_id'), table_name='google_credential')
    op.drop_index(op.f('ix_google_credential_id'), table_name='google_credential')
    op.drop_table('google_credential')
    op.drop_index(op.f('ix_gmail_label_user_id'), table_name='gmail_label')
    op.drop_index(op.f('ix_gmail_label_id'), table_name='gmail_label')
    op.drop_index(op.f('ix_gmail_label_gmail_id'), table_name='gmail_label')
    op.drop_table('gmail_label')
    # ### end Alembic commands ###
