"""add_follow_up_fields_to_email

Revision ID: 560e8285590a
Revises: 03a313a35640
Create Date: 2026-02-12 22:11:11.342961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '560e8285590a'
down_revision: Union[str, None] = '03a313a35640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailinsight', sa.Column('follow_up_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('emailinsight', sa.Column('follow_up_deadline', sa.DateTime(), nullable=True))
    op.add_column('emailinsight', sa.Column('waiting_on_reply', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emailinsight', 'waiting_on_reply')
    op.drop_column('emailinsight', 'follow_up_deadline')
    op.drop_column('emailinsight', 'follow_up_status')
    # ### end Alembic commands ###
