"""add_rule_priority

Revision ID: 57ba65cc309d
Revises: 174f9dd9f87f
Create Date: 2026-01-27 11:53:17.203387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '57ba65cc309d'
down_revision: Union[str, None] = '174f9dd9f87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'priority')
    # ### end Alembic commands ###
