"""add_is_preview_to_email_insight

Revision ID: 6036fa902ef5
Revises: 544ccc4347e7
Create Date: 2026-01-27 12:23:03.504178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6036fa902ef5'
down_revision: Union[str, None] = '544ccc4347e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailinsight', sa.Column('is_preview', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emailinsight', 'is_preview')
    # ### end Alembic commands ###
