"""Add tasks table

Revision ID: 837a83b88eea
Revises: b1c2d3e4f5a6
Create Date: 2026-02-23 08:32:27.590720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '837a83b88eea'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emailinsight', 'classification_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('task', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('task', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('task', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('user', sa.Column('digest_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user', sa.Column('digest_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=sa.text("'daily'")))
    op.add_column('user', sa.Column('digest_time_local', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'digest_time_local')
    op.drop_column('user', 'digest_frequency')
    op.drop_column('user', 'digest_enabled')
    op.alter_column('task', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('emailinsight', 'classification_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
