"""Add tasks table

Revision ID: 837a83b88eea
Revises: b1c2d3e4f5a6
Create Date: 2026-02-23 08:32:27.590720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '837a83b88eea'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emailinsight', 'classification_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
               
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if not inspector.has_table('task'):
        op.create_table('task',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('email_id', sa.Uuid(), nullable=True),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending'),
        sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='medium'),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(['email_id'], ['emailinsight.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
        op.create_index(op.f('ix_task_title'), 'task', ['title'], unique=False)
    else:
        op.alter_column('task', 'status',
                   existing_type=sa.VARCHAR(),
                   nullable=False,
                   existing_server_default=sa.text("'pending'::character varying"))
        op.alter_column('task', 'priority',
                   existing_type=sa.VARCHAR(),
                   nullable=False,
                   existing_server_default=sa.text("'medium'::character varying"))
        op.alter_column('task', 'created_at',
                   existing_type=postgresql.TIMESTAMP(),
                   nullable=False)
        op.alter_column('task', 'updated_at',
                   existing_type=postgresql.TIMESTAMP(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('emailinsight', 'classification_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
