"""add_email_intelligence_schema

Revision ID: 98134cceb82f
Revises: 2dff9cf57437
Create Date: 2026-01-26 00:16:38.058222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98134cceb82f'
down_revision: Union[str, None] = '2dff9cf57437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userintentpreference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferred_group_id', sa.Integer(), nullable=True),
    sa.Column('importance_adjustment', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userintentpreference_id'), 'userintentpreference', ['id'], unique=False)
    op.create_index(op.f('ix_userintentpreference_user_id'), 'userintentpreference', ['user_id'], unique=False)
    op.add_column('emailinsight', sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('emailinsight', sa.Column('urgency', sqlmodel.sql.sqltypes.AutoString(), server_default='low', nullable=False))
    op.add_column('emailinsight', sa.Column('needs_reply', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('emailinsight', sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emailinsight', 'explanation')
    op.drop_column('emailinsight', 'needs_reply')
    op.drop_column('emailinsight', 'urgency')
    op.drop_column('emailinsight', 'intent')
    op.drop_index(op.f('ix_userintentpreference_user_id'), table_name='userintentpreference')
    op.drop_index(op.f('ix_userintentpreference_id'), table_name='userintentpreference')
    op.drop_table('userintentpreference')
    # ### end Alembic commands ###
