"""add_preferred_group_name_to_preferences

Revision ID: a681b0ddc3a1
Revises: a1b2c3d4e5f6
Create Date: 2026-02-12 21:41:04.515509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a681b0ddc3a1'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userintentpreference', sa.Column('preferred_group_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userintentpreference', 'preferred_group_name')
    # ### end Alembic commands ###
