"""add_gmail_watch_and_processed_message_tables

Revision ID: b5eb4309bdb8
Revises: b0c1d2e3f4g5
Create Date: 2026-03-26 08:46:23.895389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5eb4309bdb8'
down_revision: Union[str, None] = 'b0c1d2e3f4g5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmailwatch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('history_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmailwatch_id'), 'gmailwatch', ['id'], unique=False)
    op.create_index(op.f('ix_gmailwatch_user_id'), 'gmailwatch', ['user_id'], unique=True)
    op.create_table('processedmessage',
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_processedmessage_user_id'), 'processedmessage', ['user_id'], unique=False)
    op.alter_column('autocleanrule', 'conditions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('user', sa.Column('enable_label_colors', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'enable_label_colors')
    op.alter_column('autocleanrule', 'conditions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_processedmessage_user_id'), table_name='processedmessage')
    op.drop_table('processedmessage')
    op.drop_index(op.f('ix_gmailwatch_user_id'), table_name='gmailwatch')
    op.drop_index(op.f('ix_gmailwatch_id'), table_name='gmailwatch')
    op.drop_table('gmailwatch')
    # ### end Alembic commands ###
