"""add_ai_log_table

Revision ID: ca6522051b5e
Revises: 1846ebe0a8fd
Create Date: 2026-02-12 23:57:59.047908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca6522051b5e'
down_revision: Union[str, None] = '1846ebe0a8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ailog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email_id', sa.Uuid(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_messages', sa.JSON(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('response_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parsed_result', sa.JSON(), nullable=True),
    sa.Column('finish_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ailog_email_id'), 'ailog', ['email_id'], unique=False)
    op.create_index(op.f('ix_ailog_id'), 'ailog', ['id'], unique=False)
    op.create_index(op.f('ix_ailog_user_id'), 'ailog', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ailog_user_id'), table_name='ailog')
    op.drop_index(op.f('ix_ailog_id'), table_name='ailog')
    op.drop_index(op.f('ix_ailog_email_id'), table_name='ailog')
    op.drop_table('ailog')
    # ### end Alembic commands ###
