"""add_onboarding_schema

Revision ID: d92f7fe374df
Revises: 10cd786660ee
Create Date: 2026-01-26 13:12:09.323149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd92f7fe374df'
down_revision: Union[str, None] = '10cd786660ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('onboarding_step', sqlmodel.sql.sqltypes.AutoString(), server_default='welcome', nullable=False))
    op.add_column('user', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'onboarding_completed')
    op.drop_column('user', 'onboarding_step')
    # ### end Alembic commands ###
