"""Add auto_create_events to User

Revision ID: f6c93cd09ad2
Revises: 03915c9c7456
Create Date: 2026-02-26 07:18:56.957299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6c93cd09ad2'
down_revision: Union[str, None] = '03915c9c7456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auto_create_events', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auto_create_events')
    # ### end Alembic commands ###
