from contextlib import asynccontextmanager
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.types import ASGIApp, Receive, Scope, Send
from starlette.datastructures import MutableHeaders
from app.core.config import settings
from app.api.v1.api import api_router
from app.db.init_db import init_db
import logging
import re

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.FileHandler("app.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

# ── Allowed Origins ──────────────────────────────────────────────
# Single source of truth for all CORS allowed origins.
ALLOWED_ORIGINS = [
    "https://mail-os.vercel.app",
    "https://www.mailos.in",
    "https://mailos.in",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# Regex that matches any *.vercel.app deployment + mailos.in (www or naked)
ALLOWED_ORIGIN_RE = re.compile(
    r"^https://.*\.vercel\.app$|^https://(?:www\.)?mailos\.in$"
)


def _origin_is_allowed(origin: str | None) -> bool:
    """Return True when *origin* should be granted CORS access."""
    if not origin:
        return False
    return origin in ALLOWED_ORIGINS or bool(ALLOWED_ORIGIN_RE.match(origin))


# ── Bulletproof CORS Middleware ──────────────────────────────────
# FastAPI's built-in CORSMiddleware does NOT attach headers when the
# downstream app raises an unhandled exception that propagates all
# the way through the ASGI stack (e.g. database crash during
# dependency injection).  This raw ASGI wrapper sits *outside* every
# other middleware and guarantees CORS headers on every response —
# even 500 error pages produced by Uvicorn itself.

class AlwaysCORSMiddleware:
    """
    ASGI middleware that injects Access-Control-* headers on EVERY
    HTTP response, including error pages generated by lower-level
    exception handlers or Uvicorn itself.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        # Extract the Origin header from the ASGI scope
        origin: str | None = None
        for header_name, header_value in scope.get("headers", []):
            if header_name == b"origin":
                origin = header_value.decode("latin-1")
                break

        # If origin isn't allowed, pass through untouched
        if not _origin_is_allowed(origin):
            await self.app(scope, receive, send)
            return

        # Wrap the send callable to inject CORS headers
        async def send_with_cors(message: dict) -> None:
            if message["type"] == "http.response.start":
                headers = MutableHeaders(scope=message)
                headers.append("Access-Control-Allow-Origin", origin)
                headers.append("Access-Control-Allow-Credentials", "true")
                headers.append("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
                headers.append("Access-Control-Allow-Headers", "*")
                headers.append("Vary", "Origin")
            await send(message)

        # Handle preflight here as a safety net
        method = scope.get("method", "")
        if method == "OPTIONS":
            await send_with_cors({
                "type": "http.response.start",
                "status": 200,
                "headers": [],
            })
            await send({"type": "http.response.body", "body": b"OK"})
            return

        try:
            await self.app(scope, receive, send_with_cors)
        except Exception:
            # If the app crashes catastrophically, still return a
            # CORS-enabled 500 so the browser exposes the real error.
            logger.exception("ASGI-level crash — sending CORS 500")
            await send_with_cors({
                "type": "http.response.start",
                "status": 500,
                "headers": [[b"content-type", b"application/json"]],
            })
            await send({
                "type": "http.response.body",
                "body": b'{"detail":"Internal server error"}',
            })


# Background scheduler (optional, only starts if apscheduler is installed)
scheduler = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global scheduler
    # Startup
    logger.info("Initializing Database...")
    try:
        init_db()
    except Exception as e:
        logger.error(f"Database initialization failed: {e}")

    # Start background sync scheduler
    try:
        from apscheduler.schedulers.background import BackgroundScheduler
        from app.services.sync_worker import run_background_sync

        scheduler = BackgroundScheduler()
        scheduler.add_job(
            run_background_sync,
            "interval",
            hours=1,
            id="gmail_background_sync",
            name="Gmail Background Sync",
            replace_existing=True,
        )
        scheduler.start()
        logger.info("Background sync scheduler started (every 1 hour)")
    except ImportError:
        logger.warning(
            "APScheduler not installed. Background sync disabled. "
            "Install with: pip install apscheduler"
        )
    except Exception as e:
        logger.error(f"Failed to start background scheduler: {e}")

    yield

    # Shutdown
    if scheduler:
        scheduler.shutdown(wait=False)
        logger.info("Background sync scheduler stopped")


app = FastAPI(
    title=settings.PROJECT_NAME,
    openapi_url=f"{settings.API_V1_STR}/openapi.json",
    lifespan=lifespan,
    debug=settings.DEBUG,
)

# ── Standard CORSMiddleware (handles happy-path responses) ──────
app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_origin_regex=r"https://.*\.vercel\.app|https://(?:www\.)?mailos\.in",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Exception handlers (backup CORS for caught exceptions) ──────

@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request: Request, exc: StarletteHTTPException):
    content = {"detail": exc.detail} if isinstance(exc.detail, str) else exc.detail
    origin = request.headers.get("origin")
    headers = {}
    if _origin_is_allowed(origin):
        headers["Access-Control-Allow-Origin"] = origin
        headers["Access-Control-Allow-Credentials"] = "true"
    return JSONResponse(status_code=exc.status_code, content=content, headers=headers)


@app.exception_handler(Exception)
async def general_exception_handler(request: Request, exc: Exception):
    logger.exception("Unhandled exception: %s", exc)
    origin = request.headers.get("origin")
    headers = {}
    if _origin_is_allowed(origin):
        headers["Access-Control-Allow-Origin"] = origin
        headers["Access-Control-Allow-Credentials"] = "true"
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error"},
        headers=headers,
    )


app.include_router(api_router, prefix=settings.API_V1_STR)


@app.get("/")
def root():
    return {"message": "Welcome to MailOS Backend"}


# ── Mount the bulletproof CORS wrapper OUTSIDE the FastAPI stack ─
# This MUST be the outermost layer so it catches everything.
# Uvicorn will serve `app` which is now: AlwaysCORSMiddleware → FastAPI
app = AlwaysCORSMiddleware(app)

